services:
  serge:
    #image: ghcr.io/amperecomputingai/ampere-ai-serge-chat:0.0.8
    image: ghcr.io/amperecomputingai/ampere-ai-serge-chat:0.0.8-ol9
    container_name: serge-app
    build:
      context: ./serge
      dockerfile: ../Dockerfile.ol9
      target: release
    restart: unless-stopped
    ports:
      - 8008:8008
    volumes:
      - weights:/usr/src/app/weights
      - datadb:/data/db/

volumes:
  weights:
  datadb:
